[tool.poetry]
name = "boids-service"
version = "1.0.2"
description = "Back-end Python service which implements the Boid behavior"
authors = ["Kerry Johnson <kerry.t.johnson@gmail.com>"]
readme = "README.md"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version = "1.0.2"
version_files = [
    "pyproject.toml:^version"
]

[tool.poetry.dependencies]
python = "^3.10"
PyYAML = "^6.0"
python-dateutil = "^2.8.2"
urllib3 = "^2.0.2"
boids-utils = "^1.1.5"

[tool.poetry.group.dev.dependencies]
commitizen = "^2.40.0"
pylint = "^2.15.10"
black = "^24.3.0"


[tool.poetry.group.test.dependencies]
pytest-asyncio = "^0.21.1"
pytest-timeout = "^2.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
